/**
 * Generated by
 *    $ ./gradlew buildSrcLibs
 * Re-run when you add a new dependency to the build
 *
 * Find which updates are available by running
 *     $ ./gradlew refreshVersions
 * And edit the file `versions.properties`
 *
 * See https://github.com/jmfayard/refreshVersions
 */
object Libs {
    const val aws_lambda_java_events: String = "com.amazonaws:aws-lambda-java-events:_"

    const val com_google_devtools_ksp_com_google_devtools_ksp_gradle_plugin: String =
        "com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin:_"

    const val com_github_kt3k_coveralls_gradle_plugin: String =
        "com.github.kt3k.coveralls:com.github.kt3k.coveralls.gradle.plugin:_"

    const val h2: String = "com.h2database:h2:_"

    const val kotlinpoet: String = "com.squareup:kotlinpoet:_"

    const val kotlinpoet_ksp: String = "com.squareup:kotlinpoet-ksp:_"

    const val kotlinpoet_metadata: String = "com.squareup:kotlinpoet-metadata:_"

    const val hikaricp: String = "com.zaxxer:HikariCP:_"

    const val de_fayard_buildsrclibs_gradle_plugin: String =
        "de.fayard.buildSrcLibs:de.fayard.buildSrcLibs.gradle.plugin:_"

    const val forkhandles_bom: String = "dev.forkhandles:forkhandles-bom:_"

    const val parser4k: String = "dev.forkhandles:parser4k"

    const val result4k: String = "dev.forkhandles:result4k"

    const val values4k: String = "dev.forkhandles:values4k"

    const val io_codearte_nexus_staging_gradle_plugin: String =
        "io.codearte.nexus-staging:io.codearte.nexus-staging.gradle.plugin:_"

    const val lettuce_core: String = "io.lettuce:lettuce-core:_"

    const val mockk: String = "io.mockk:mockk:_"

    const val http4k_aws: String = "org.http4k:http4k-aws"

    const val http4k_cloudnative: String = "org.http4k:http4k-cloudnative"

    const val http4k_contract: String = "org.http4k:http4k-contract"

    const val http4k_core: String = "org.http4k:http4k-core"

    const val http4k_format_core: String = "org.http4k:http4k-format-core"

    const val http4k_format_jackson: String = "org.http4k:http4k-format-jackson"

    const val http4k_format_moshi: String = "org.http4k:http4k-format-moshi"

    const val http4k_security_oauth: String = "org.http4k:http4k-security-oauth"

    const val http4k_serverless_lambda: String = "org.http4k:http4k-serverless-lambda"

    const val http4k_template_handlebars: String = "org.http4k:http4k-template-handlebars"

    const val http4k_testing_approval: String = "org.http4k:http4k-testing-approval"

    const val http4k_testing_chaos: String = "org.http4k:http4k-testing-chaos"

    const val http4k_testing_hamkrest: String = "org.http4k:http4k-testing-hamkrest"

    const val exposed_core: String = "org.jetbrains.exposed:exposed-core:_"

    const val exposed_jdbc: String = "org.jetbrains.exposed:exposed-jdbc:_"

    const val kotlin_annotation_processing_gradle: String =
        "org.jetbrains.kotlin:kotlin-annotation-processing-gradle:_"

    const val kotlin_gradle_plugin: String = "org.jetbrains.kotlin:kotlin-gradle-plugin:_"

    const val kotlin_scripting_compiler_embeddable: String =
        "org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable:_"

    const val junit_jupiter_api: String = "org.junit.jupiter:junit-jupiter-api"

    const val junit_jupiter_engine: String = "org.junit.jupiter:junit-jupiter-engine"

    const val junit_bom: String = "org.junit:junit-bom:_"

    const val junit_jupiter: String = "org.testcontainers:junit-jupiter"

    const val testcontainers: String = "org.testcontainers:testcontainers"

    const val testcontainers_bom: String = "org.testcontainers:testcontainers-bom:_"

    const val swagger_ui: String = "org.webjars:swagger-ui:_"

    const val api: String = "se.ansman.kotshi:api:_"

    const val se_ansman_kotshi_compiler: String = "se.ansman.kotshi:compiler:_"

    const val bom: String = "software.amazon.awssdk:bom:_"

    const val cloudfront: String = "software.amazon.awssdk:cloudfront"

    const val cognitoidentityprovider: String = "software.amazon.awssdk:cognitoidentityprovider"

    const val dynamodb: String = "software.amazon.awssdk:dynamodb"

    const val kms: String = "software.amazon.awssdk:kms"

    const val lambda: String = "software.amazon.awssdk:lambda"

    const val s3: String = "software.amazon.awssdk:s3"

    const val secretsmanager: String = "software.amazon.awssdk:secretsmanager"

    const val sns: String = "software.amazon.awssdk:sns"

    const val sqs: String = "software.amazon.awssdk:sqs"

    const val ssm: String = "software.amazon.awssdk:ssm"

    const val sts: String = "software.amazon.awssdk:sts"
}
