{
  "formatVersion": "1.1",
  "component": {
    "group": "org.http4k",
    "module": "gradle-plugins",
    "version": "0.0.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.0.21",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "io.github.gradle-nexus",
          "module": "publish-plugin",
          "version": {
            "requires": "2.0.0",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.github.jk1",
          "module": "gradle-license-report",
          "version": {
            "requires": "2.9",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-base",
          "version": {
            "requires": "1.9.20",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.9.20",
            "rejects": [
              "_"
            ]
          }
        }
      ],
      "files": [
        {
          "name": "gradle-plugins-0.0.0.0.jar",
          "url": "gradle-plugins-0.0.0.0.jar",
          "size": 1440065,
          "sha512": "88fd2e41a520a011616c1c230114a8ba5051b7da6d9985f6007dec54fab8c17940b38182ff2877fc2f557e3f5eaf99ecf7f8b0829fac79719676f64ad700dd2f",
          "sha256": "4f9ef7d5f41db8372480b812996765eb61302d42301d45aac99a11d2d3ec906d",
          "sha1": "f96d8288d1b74a8761b262141e183d6e7c17ca86",
          "md5": "a0f79d1c43bd6b06fcaada182673f2f8"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.0.21",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "io.github.gradle-nexus",
          "module": "publish-plugin",
          "version": {
            "requires": "2.0.0",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.github.jk1",
          "module": "gradle-license-report",
          "version": {
            "requires": "2.9",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-base",
          "version": {
            "requires": "1.9.20",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.9.20",
            "rejects": [
              "_"
            ]
          }
        }
      ],
      "files": [
        {
          "name": "gradle-plugins-0.0.0.0.jar",
          "url": "gradle-plugins-0.0.0.0.jar",
          "size": 1440065,
          "sha512": "88fd2e41a520a011616c1c230114a8ba5051b7da6d9985f6007dec54fab8c17940b38182ff2877fc2f557e3f5eaf99ecf7f8b0829fac79719676f64ad700dd2f",
          "sha256": "4f9ef7d5f41db8372480b812996765eb61302d42301d45aac99a11d2d3ec906d",
          "sha1": "f96d8288d1b74a8761b262141e183d6e7c17ca86",
          "md5": "a0f79d1c43bd6b06fcaada182673f2f8"
        }
      ]
    }
  ]
}
