{
  "formatVersion": "1.1",
  "component": {
    "group": "org.http4k",
    "module": "gradle-plugins",
    "version": "0.0.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.10.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.0.21",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "io.github.gradle-nexus",
          "module": "publish-plugin",
          "version": {
            "requires": "2.0.0",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.github.jk1",
          "module": "gradle-license-report",
          "version": {
            "requires": "2.9",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-base",
          "version": {
            "requires": "1.9.20",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.9.20",
            "rejects": [
              "_"
            ]
          }
        }
      ],
      "files": [
        {
          "name": "gradle-plugins-0.0.0.0.jar",
          "url": "gradle-plugins-0.0.0.0.jar",
          "size": 1502150,
          "sha512": "d3cc3adf4ed414f9c2597f6d8b4db1cc301a4dcfe47f37c5a25aeacb2cc2858dbf16c9446525757fe830236d6f4ae0ad068926df61db4ccebdbe17a9669e4e8b",
          "sha256": "b9ea957db77cc8f56cbd17eb4bcd820561e6cd9987328a7bf16c12bf30e6714c",
          "sha1": "c3541f70e2422c66d2ac6c79c90780ca9cc2cc5a",
          "md5": "d4eafb58526d4c97a01d88195a58f0dc"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-gradle-plugin",
          "version": {
            "requires": "2.0.21",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "io.github.gradle-nexus",
          "module": "publish-plugin",
          "version": {
            "requires": "2.0.0",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "com.github.jk1",
          "module": "gradle-license-report",
          "version": {
            "requires": "2.9",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-base",
          "version": {
            "requires": "1.9.20",
            "rejects": [
              "_"
            ]
          }
        },
        {
          "group": "org.jetbrains.dokka",
          "module": "dokka-gradle-plugin",
          "version": {
            "requires": "1.9.20",
            "rejects": [
              "_"
            ]
          }
        }
      ],
      "files": [
        {
          "name": "gradle-plugins-0.0.0.0.jar",
          "url": "gradle-plugins-0.0.0.0.jar",
          "size": 1502150,
          "sha512": "d3cc3adf4ed414f9c2597f6d8b4db1cc301a4dcfe47f37c5a25aeacb2cc2858dbf16c9446525757fe830236d6f4ae0ad068926df61db4ccebdbe17a9669e4e8b",
          "sha256": "b9ea957db77cc8f56cbd17eb4bcd820561e6cd9987328a7bf16c12bf30e6714c",
          "sha1": "c3541f70e2422c66d2ac6c79c90780ca9cc2cc5a",
          "md5": "d4eafb58526d4c97a01d88195a58f0dc"
        }
      ]
    }
  ]
}
