name: New Release - Update other projects
on:
  repository_dispatch:
    types: [http4k-connect-release]
jobs:
  create-upgrade-branches:
    strategy:
      matrix:
        repo:
          - 'http4k/http4k-connect-examples'
    runs-on: ubuntu-latest
    steps:
      - name: Trigger ${{ matrix.repo }}
        uses: peter-evans/repository-dispatch@v2.1.1
        with:
          token: ${{ secrets.TOOLBOX_REPO_TOKEN }}
          repository: ${{ matrix.repo }}
          event-type: http4k-release
          client-payload: '{"version": "${{ github.event.client_payload.version }}"}'
