name: New Release - Twitter
on:
  repository_dispatch:
    types: [http4k-connect-release]
permissions:
  contents: read

jobs:
  tweet:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    steps:
      - uses: ethomson/send-tweet-action@v1
        with:
          status: "🎉 New http4k-connect release ${{ github.event.client_payload.version }} 🎉. Changelog available at: https://github.com/http4k/http4k-connect/blob/master/CHANGELOG.md#changelog"
          consumer-key: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
          consumer-secret: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
          access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          access-token-secret: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
